In [2]:
#11. Numpy
#numpy 라이브러리는 수치해석이나 통계 관련 기능에 특화되어 있음
# 다른 파이썬 라이브러리들과 함께 사용됨
#Pandas, matplotlib, scipy
#실행 속도가 빠른 편

In [3]:
# Numpy의 1차원 자료형 1
import numpy as np

In [4]:
a=[10,20,30,40,50]
a

[10, 20, 30, 40, 50]

In [5]:
type(a)

list

In [6]:
b=np.array(a)
b

array([10, 20, 30, 40, 50])

In [7]:
type(b) #Numpy의 자료형은 ndarray이다.

numpy.ndarray

In [8]:
print(b)

[10 20 30 40 50]


In [9]:
b.shape

(5,)

In [10]:
c=np.array([5,4,3,2,1])
c

array([5, 4, 3, 2, 1])

In [11]:
b+c

array([15, 24, 33, 42, 51])

In [12]:
b+5

array([15, 25, 35, 45, 55])

In [13]:
a+5 # 넘파이에서 가능한 것!

TypeError: can only concatenate list (not "int") to list

In [14]:
a+[5,4,3,2,1] # 더하는 것이 아닌 나열하게 된다.

[10, 20, 30, 40, 50, 5, 4, 3, 2, 1]

In [15]:
# Numpy의 1차원 자료형 2

In [16]:
np.sum(b)

150

In [17]:
np.mean(b)

30.0

In [18]:
np.max(b)

50

In [19]:
np.min(b)

10

In [20]:
c=b/3
c

array([ 3.33333333,  6.66666667, 10.        , 13.33333333, 16.66666667])

In [21]:
np.round(c,1) #소수점 첫번째 자리까지 반올림

array([ 3.3,  6.7, 10. , 13.3, 16.7])

In [22]:
np.round(c,3)

array([ 3.333,  6.667, 10.   , 13.333, 16.667])

In [23]:
np.round(c,0)

array([ 3.,  7., 10., 13., 17.])

In [24]:
b[0]

10

In [25]:
b[-1]

50

In [26]:
b[1:3]

array([20, 30])

In [27]:
b[2:]

array([30, 40, 50])

In [28]:
np.sum(b[2:])

120

In [29]:
np.mean(b[2:])

40.0

In [30]:
b[1]=200
b

array([ 10, 200,  30,  40,  50])

In [31]:
d=np.arange(5)
d

array([0, 1, 2, 3, 4])

In [32]:
e=np.arange(3,8)
e

array([3, 4, 5, 6, 7])

In [33]:
f=np.arange(3,8,2)
f

array([3, 5, 7])

In [34]:
g=np.zeros(5)
g

array([0., 0., 0., 0., 0.])

In [35]:
h=np.ones(5)
h

array([1., 1., 1., 1., 1.])

In [36]:
b

array([ 10, 200,  30,  40,  50])

In [37]:
bb=b
bb

array([ 10, 200,  30,  40,  50])

In [38]:
bb[0]=100
bb

array([100, 200,  30,  40,  50])

In [39]:
b #b도 바뀜

array([100, 200,  30,  40,  50])

In [40]:
bb=b.copy() # 복사
bb[2]=300

In [41]:
b # 원래 b 유지됨.

array([100, 200,  30,  40,  50])

In [42]:
bb # bb만 적용됨.

array([100, 200, 300,  40,  50])

In [43]:
# Numpy의 2차원 자료형_01
# 2차원적인 데이터 형식
# 행렬 연산이 가능함.
a=np.array([[10,20,30,40],[50,60,70,80]])
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [44]:
a.shape

(2, 4)

In [45]:
b,c = a.shape

In [46]:
b

2

In [47]:
c

4

In [48]:
a[0,0]

10

In [49]:
a[-1,-1]

80

In [50]:
a[1,1:]

array([60, 70, 80])

In [51]:
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [52]:
a[0,1]=2

In [53]:
a

array([[10,  2, 30, 40],
       [50, 60, 70, 80]])

In [54]:
b=np.zeros((2,4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [55]:
c=np.ones((3,5))

In [56]:
c

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [57]:
c=np.arange(8)
c

array([0, 1, 2, 3, 4, 5, 6, 7])

In [58]:
c.reshape(2,4) #저장되지는 않는다.

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [59]:
c

array([0, 1, 2, 3, 4, 5, 6, 7])

In [60]:
c= c.reshape(2,4)
c # 저장하기

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [61]:
c=c.reshape(4,2)
c

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [62]:
c.sum()

28

In [63]:
d=c.copy()
d[0,0]=10
d

array([[10,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7]])

In [64]:
c

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [65]:
c==d

array([[False,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

In [66]:
e=np.arange(49).reshape(7,7)
e

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48]])

In [67]:
e[:,1:3]

array([[ 1,  2],
       [ 8,  9],
       [15, 16],
       [22, 23],
       [29, 30],
       [36, 37],
       [43, 44]])

In [68]:
e[3:,:4]

array([[21, 22, 23, 24],
       [28, 29, 30, 31],
       [35, 36, 37, 38],
       [42, 43, 44, 45]])

In [69]:
e[3:,:4].sum()

528

In [70]:
f=e[3:,:4].copy()
f

array([[21, 22, 23, 24],
       [28, 29, 30, 31],
       [35, 36, 37, 38],
       [42, 43, 44, 45]])

In [71]:
e[4,0]=100
e

array([[  0,   1,   2,   3,   4,   5,   6],
       [  7,   8,   9,  10,  11,  12,  13],
       [ 14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27],
       [100,  29,  30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39,  40,  41],
       [ 42,  43,  44,  45,  46,  47,  48]])

In [72]:
f  #복사를 해서 영향 없다.

array([[21, 22, 23, 24],
       [28, 29, 30, 31],
       [35, 36, 37, 38],
       [42, 43, 44, 45]])

In [73]:
# Numpy의 기본 연산과 조건 처리_01
# 사칙연산, 스칼라곱, 행렬곱
a=np.arange(5,45,5).reshape(2,4)
b=np.arange(20,36,2).reshape(2,4)
a

array([[ 5, 10, 15, 20],
       [25, 30, 35, 40]])

In [74]:
b

array([[20, 22, 24, 26],
       [28, 30, 32, 34]])

In [75]:
a-b

array([[-15, -12,  -9,  -6],
       [ -3,   0,   3,   6]])

In [76]:
a+b

array([[25, 32, 39, 46],
       [53, 60, 67, 74]])

In [77]:
b-a

array([[15, 12,  9,  6],
       [ 3,  0, -3, -6]])

In [78]:
a*b #행렬곱이 아닌 같은 자리에 있는 숫자끼리 곱셈

array([[ 100,  220,  360,  520],
       [ 700,  900, 1120, 1360]])

In [79]:
a/b

array([[0.25      , 0.45454545, 0.625     , 0.76923077],
       [0.89285714, 1.        , 1.09375   , 1.17647059]])

In [80]:
a//b

array([[0, 0, 0, 0],
       [0, 1, 1, 1]], dtype=int32)

In [81]:
a%b

array([[ 5, 10, 15, 20],
       [25,  0,  3,  6]], dtype=int32)

In [82]:
a*10

array([[ 50, 100, 150, 200],
       [250, 300, 350, 400]])

In [83]:
c=a*10
c

array([[ 50, 100, 150, 200],
       [250, 300, 350, 400]])

In [84]:
b

array([[20, 22, 24, 26],
       [28, 30, 32, 34]])

In [85]:
bb=b.reshape(4,2)
bb

array([[20, 22],
       [24, 26],
       [28, 30],
       [32, 34]])

In [86]:
a@bb #행렬 곱셈

array([[1400, 1500],
       [3480, 3740]])

In [87]:
# Numpy의 기본 연산과 조건 처리_02
a=np.arange(1,15)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [88]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True])

In [89]:
a==5

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False])

In [90]:
a[a>5] # 5보다 큰 수만 볼 수 있다.

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [91]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [92]:
a[a<5]=5 #5보다 작은 수들을 5로 바꿔줌.
a

array([ 5,  5,  5,  5,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [93]:
a[a>10]=10
a

array([ 5,  5,  5,  5,  5,  6,  7,  8,  9, 10, 10, 10, 10, 10])