In [1]:
# 12. Pandas
# 데이터 분석 업무의 80% 정도가 데이터를 수집하고 정제하는 과정.
# pandas 라이브러리는 데이터를 수집하고 정제하기에 적합.
# 2차원 데이터에 강점이 있음
# 공통된 형태로 데이터를 정리하기에 유용함
# 실행 속도가 빠른 편임

In [2]:
# Pandas의 1차원 자료형 - Series
# 파이썬의 딕셔너리와 유사함.
import pandas as pd
import numpy as np

In [3]:
a={'a':10,'b':20,'c':30,'d':40,'e':50}
type(a)

dict

In [4]:
b=pd.Series(a)
b

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [5]:
type(b)

pandas.core.series.Series

In [6]:
b.shape

(5,)

In [7]:
aa=np.arange(3,10)
aa

array([3, 4, 5, 6, 7, 8, 9])

In [8]:
bb=pd.Series(aa)
bb

0    3
1    4
2    5
3    6
4    7
5    8
6    9
dtype: int32

In [9]:
type(bb)

pandas.core.series.Series

In [10]:
bb.shape

(7,)

In [11]:
a

{'a': 10, 'b': 20, 'c': 30, 'd': 40, 'e': 50}

In [12]:
a.keys()

dict_keys(['a', 'b', 'c', 'd', 'e'])

In [13]:
a.values()

dict_values([10, 20, 30, 40, 50])

In [14]:
b

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [15]:
b.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [16]:
b.values

array([10, 20, 30, 40, 50], dtype=int64)

In [17]:
c=[10,20,30,40,50]
d=pd.Series(c)
d

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [18]:
type(d)

pandas.core.series.Series

In [19]:
d.shape

(5,)

In [20]:
d.index

RangeIndex(start=0, stop=5, step=1)

In [21]:
d.values

array([10, 20, 30, 40, 50], dtype=int64)

In [22]:
e=['a','b','c','d','e']

In [23]:
f=[10,20,30,40,50]

In [24]:
g=pd.Series(f, index=e)
g

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [25]:
g['a']

10

In [26]:
g[0]

10

In [27]:
g['a':'d'] # d까지 다 포함되서 출력 (인덱스 이름)

a    10
b    20
c    30
d    40
dtype: int64

In [28]:
g[0:4] # 마지막 4행은 제외되고 출력됨

a    10
b    20
c    30
d    40
dtype: int64

In [29]:
# Pandas의 2차원 자료형 - DataFrame_01
import pandas as pd

In [30]:
a={'a':[1,2,3],'b':[1,3,5],'c':[2,4,6],'d':[3,6,9]}
a

{'a': [1, 2, 3], 'b': [1, 3, 5], 'c': [2, 4, 6], 'd': [3, 6, 9]}

In [31]:
df1=pd.DataFrame(a)
df1

a  b  c  d
0  1  1  2  3
1  2  3  4  6
2  3  5  6  9

In [32]:
type(df1)

pandas.core.frame.DataFrame

In [33]:
df1.shape

(3, 4)

In [34]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
a    3 non-null int64
b    3 non-null int64
c    3 non-null int64
d    3 non-null int64
dtypes: int64(4)
memory usage: 176.0 bytes


In [35]:
df2=np.arange(12).reshape(3,4)

In [36]:
df2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
df2.shape

(3, 4)

In [38]:
df=pd.DataFrame([[1,20,'서울'],[2,25,'대전']],
                   index = ['홍길동','홍길순'],
                   columns = ['순서','나이','지역'])

In [39]:
df

순서  나이  지역
홍길동   1  20  서울
홍길순   2  25  대전

In [40]:
type(df)

pandas.core.frame.DataFrame

In [41]:
df.shape

(2, 3)

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, 홍길동 to 홍길순
Data columns (total 3 columns):
순서    2 non-null int64
나이    2 non-null int64
지역    2 non-null object
dtypes: int64(2), object(1)
memory usage: 64.0+ bytes


In [43]:
df.index

Index(['홍길동', '홍길순'], dtype='object')

In [44]:
df.values

array([[1, 20, '서울'],
       [2, 25, '대전']], dtype=object)

In [45]:
df.columns

Index(['순서', '나이', '지역'], dtype='object')

In [46]:
df.index=['사람 1','사람 2']
df

순서  나이  지역
사람 1   1  20  서울
사람 2   2  25  대전

In [47]:
df.columns=['연번','연령','도시']
df

연번  연령  도시
사람 1   1  20  서울
사람 2   2  25  대전

In [48]:
df=df.rename(index={'사람 1':'홍길동'})

In [49]:
df

연번  연령  도시
홍길동    1  20  서울
사람 2   2  25  대전

In [50]:
df=df.rename(columns={'연번':'순서','연령':'나이'})

In [51]:
df

순서  나이  도시
홍길동    1  20  서울
사람 2   2  25  대전

In [52]:
# Pandas의 2차원 자료형 - DataFrame_02

In [53]:
df

순서  나이  도시
홍길동    1  20  서울
사람 2   2  25  대전

In [54]:
df.loc['사람 3']=[3, 30,'부산']

In [55]:
df

순서  나이  도시
홍길동    1  20  서울
사람 2   2  25  대전
사람 3   3  30  부산

In [56]:
df.loc['사람 4']=0
df

순서  나이  도시
홍길동    1  20  서울
사람 2   2  25  대전
사람 3   3  30  부산
사람 4   0   0   0

In [57]:
df.loc['사람 1']=df.loc['홍길동']

In [58]:
df

순서  나이  도시
홍길동    1  20  서울
사람 2   2  25  대전
사람 3   3  30  부산
사람 4   0   0   0
사람 1   1  20  서울

In [59]:
df['나이대']=['20대','20대','30대','0대','20대']
df

순서  나이  도시  나이대
홍길동    1  20  서울  20대
사람 2   2  25  대전  20대
사람 3   3  30  부산  30대
사람 4   0   0   0   0대
사람 1   1  20  서울  20대

In [60]:
df['직업']='학생'
df

순서  나이  도시  나이대  직업
홍길동    1  20  서울  20대  학생
사람 2   2  25  대전  20대  학생
사람 3   3  30  부산  30대  학생
사람 4   0   0   0   0대  학생
사람 1   1  20  서울  20대  학생

In [61]:
df.loc['사람 4','순서']=4
df

순서  나이  도시  나이대  직업
홍길동    1  20  서울  20대  학생
사람 2   2  25  대전  20대  학생
사람 3   3  30  부산  30대  학생
사람 4   4   0   0   0대  학생
사람 1   1  20  서울  20대  학생

In [62]:
df.iloc[3,1] = 10
df

순서  나이  도시  나이대  직업
홍길동    1  20  서울  20대  학생
사람 2   2  25  대전  20대  학생
사람 3   3  30  부산  30대  학생
사람 4   4  10   0   0대  학생
사람 1   1  20  서울  20대  학생

In [63]:
df.loc['사람 4',['도시','나이대']]='광주','10대'
df

순서  나이  도시  나이대  직업
홍길동    1  20  서울  20대  학생
사람 2   2  25  대전  20대  학생
사람 3   3  30  부산  30대  학생
사람 4   4  10  광주  10대  학생
사람 1   1  20  서울  20대  학생

In [64]:
df.iloc[3,[1,3]] = 40, '40대'
df

순서  나이  도시  나이대  직업
홍길동    1  20  서울  20대  학생
사람 2   2  25  대전  20대  학생
사람 3   3  30  부산  30대  학생
사람 4   4  40  광주  40대  학생
사람 1   1  20  서울  20대  학생

In [65]:
df= df.drop('사람 4', axis=0)
df

순서  나이  도시  나이대  직업
홍길동    1  20  서울  20대  학생
사람 2   2  25  대전  20대  학생
사람 3   3  30  부산  30대  학생
사람 1   1  20  서울  20대  학생

In [66]:
df=df.drop(['나이대','직업'],axis=1)
df

순서  나이  도시
홍길동    1  20  서울
사람 2   2  25  대전
사람 3   3  30  부산
사람 1   1  20  서울

In [67]:
# Pandas의 2차원 자료형 - DataFrame_03
df2=df
df2

순서  나이  도시
홍길동    1  20  서울
사람 2   2  25  대전
사람 3   3  30  부산
사람 1   1  20  서울

In [68]:
df2.loc['사람 1','순서']=4
df2

순서  나이  도시
홍길동    1  20  서울
사람 2   2  25  대전
사람 3   3  30  부산
사람 1   4  20  서울

In [69]:
df

순서  나이  도시
홍길동    1  20  서울
사람 2   2  25  대전
사람 3   3  30  부산
사람 1   4  20  서울

In [70]:
df3=df.copy()

In [71]:
df3

순서  나이  도시
홍길동    1  20  서울
사람 2   2  25  대전
사람 3   3  30  부산
사람 1   4  20  서울

In [72]:
df3.loc['사람 1','순서']= 5
df3

순서  나이  도시
홍길동    1  20  서울
사람 2   2  25  대전
사람 3   3  30  부산
사람 1   5  20  서울

In [73]:
df

순서  나이  도시
홍길동    1  20  서울
사람 2   2  25  대전
사람 3   3  30  부산
사람 1   4  20  서울

In [74]:
hong=df.loc['홍길동']
hong

순서     1
나이    20
도시    서울
Name: 홍길동, dtype: object

In [75]:
type(hong)

pandas.core.series.Series

In [76]:
hong.shape

(3,)

In [77]:
gil=df.iloc[0]
gil

순서     1
나이    20
도시    서울
Name: 홍길동, dtype: object

In [78]:
type(gil)

pandas.core.series.Series

In [79]:
gil.shape

(3,)

In [80]:
df4=df.loc[['홍길동','사람 1']]
df4

순서  나이  도시
홍길동    1  20  서울
사람 1   4  20  서울

In [81]:
type(df4)

pandas.core.frame.DataFrame

In [82]:
df5=df.iloc[[0,3]]
df5

순서  나이  도시
홍길동    1  20  서울
사람 1   4  20  서울

In [83]:
df6=df.loc['홍길동':'사람 3']
df6

순서  나이  도시
홍길동    1  20  서울
사람 2   2  25  대전
사람 3   3  30  부산

In [84]:
df7=df.iloc[0:3]
df7

순서  나이  도시
홍길동    1  20  서울
사람 2   2  25  대전
사람 3   3  30  부산

In [85]:
df

순서  나이  도시
홍길동    1  20  서울
사람 2   2  25  대전
사람 3   3  30  부산
사람 1   4  20  서울

In [86]:
df8=df[['나이']] # 데이터프레임 구조
df8

나이
홍길동   20
사람 2  25
사람 3  30
사람 1  20

In [87]:
df9=df['나이'] #시리즈로 출력된다.
df9

홍길동     20
사람 2    25
사람 3    30
사람 1    20
Name: 나이, dtype: int64

In [88]:
type(df8)

pandas.core.frame.DataFrame

In [89]:
type(df9)

pandas.core.series.Series

In [90]:
df10=df[['나이','도시']]
df10

나이  도시
홍길동   20  서울
사람 2  25  대전
사람 3  30  부산
사람 1  20  서울

In [91]:
df

순서  나이  도시
홍길동    1  20  서울
사람 2   2  25  대전
사람 3   3  30  부산
사람 1   4  20  서울

In [92]:
df11=df.loc[['홍길동','사람 1'],['나이','도시']]
df11

나이  도시
홍길동   20  서울
사람 1  20  서울

In [93]:
df12=df.iloc[[0,3],[1,2]]
df12

나이  도시
홍길동   20  서울
사람 1  20  서울

In [94]:
# Pandas의 2차원 자료형 - DataFrame_04
a={'이름' :['홍길동','사람 1','사람 2'],'나이' : [20,30,25],
      '도시' : ['서울','서울','대전']}
df=pd.DataFrame(a)
df

이름  나이  도시
0   홍길동  20  서울
1  사람 1  30  서울
2  사람 2  25  대전

In [95]:
df2=df.set_index(['이름'])
df2

나이  도시
이름          
홍길동   20  서울
사람 1  30  서울
사람 2  25  대전

In [96]:
df3=df.set_index(['도시'])
df3

이름  나이
도시          
서울   홍길동  20
서울  사람 1  30
대전  사람 2  25

In [97]:
df2

나이  도시
이름          
홍길동   20  서울
사람 1  30  서울
사람 2  25  대전

In [98]:
df3=df2.reset_index()
df3

이름  나이  도시
0   홍길동  20  서울
1  사람 1  30  서울
2  사람 2  25  대전

In [99]:
df3=df3.set_index(['도시'])
df3

이름  나이
도시          
서울   홍길동  20
서울  사람 1  30
대전  사람 2  25

In [100]:
df2

나이  도시
이름          
홍길동   20  서울
사람 1  30  서울
사람 2  25  대전

In [101]:
df2['나이대']=['30대','20대','30대']

In [102]:
df2=df2.sort_index(ascending=True)
df2

나이  도시  나이대
이름               
사람 1  30  서울  20대
사람 2  25  대전  30대
홍길동   20  서울  30대

In [103]:
df2=df2.sort_index(ascending=False)
df2

나이  도시  나이대
이름               
홍길동   20  서울  30대
사람 2  25  대전  30대
사람 1  30  서울  20대

In [104]:
df2=df2.sort_values(by='나이',ascending=True)
df2


나이  도시  나이대
이름               
홍길동   20  서울  30대
사람 2  25  대전  30대
사람 1  30  서울  20대

In [105]:
df2=df2.T
df2

이름   홍길동 사람 2 사람 1
나이    20   25   30
도시    서울   대전   서울
나이대  30대  30대  20대

In [106]:
df2=df2.T
df2

나이  도시  나이대
이름               
홍길동   20  서울  30대
사람 2  25  대전  30대
사람 1  30  서울  20대

In [107]:
df2=df2.reset_index()
df2

이름  나이  도시  나이대
0   홍길동  20  서울  30대
1  사람 2  25  대전  30대
2  사람 1  30  서울  20대

In [108]:
df2=df2.set_index(['이름'])
df2

나이  도시  나이대
이름               
홍길동   20  서울  30대
사람 2  25  대전  30대
사람 1  30  서울  20대

In [109]:
df2=df2.sort_index(ascending=True)
df2

나이  도시  나이대
이름               
사람 1  30  서울  20대
사람 2  25  대전  30대
홍길동   20  서울  30대

In [110]:
df2=df2.reset_index()
df2

이름  나이  도시  나이대
0  사람 1  30  서울  20대
1  사람 2  25  대전  30대
2   홍길동  20  서울  30대

In [111]:
b={'20대' : 2, '30대' : 3}

In [112]:
df2['나이대']=df2['나이대'].map(b)
df2

이름  나이  도시  나이대
0  사람 1  30  서울    2
1  사람 2  25  대전    3
2   홍길동  20  서울    3

In [113]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
이름     3 non-null object
나이     3 non-null object
도시     3 non-null object
나이대    3 non-null int64
dtypes: int64(1), object(3)
memory usage: 176.0+ bytes


In [114]:
# Pandas의 기본 연산_01
# 기본 연산 - Series
a={'a':10,'b':20,'c':30,'d':40,'e':50}

In [115]:
a

{'a': 10, 'b': 20, 'c': 30, 'd': 40, 'e': 50}

In [116]:
b=pd.Series(a)
b

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [117]:
type(b)

pandas.core.series.Series

In [118]:
c=b/10
c

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
dtype: float64

In [119]:
c=b//10
c

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [120]:
type(c)

pandas.core.series.Series

In [121]:
d=b+c
d

a    11
b    22
c    33
d    44
e    55
dtype: int64

In [122]:
e={'a':10,'c':20,'e':30,'g':40}
f=pd.Series(e)
f

a    10
c    20
e    30
g    40
dtype: int64

In [123]:
d+f

a    21.0
b     NaN
c    53.0
d     NaN
e    85.0
g     NaN
dtype: float64

In [124]:
d.add(f, fill_value=0) # 결측치에 0으로 더하게 함.

a    21.0
b    22.0
c    53.0
d    44.0
e    85.0
g    40.0
dtype: float64

In [125]:
d.sub(f,fill_value=0)

a     1.0
b    22.0
c    13.0
d    44.0
e    25.0
g   -40.0
dtype: float64

In [126]:
d.mul(f,fill_value=0)

a     110.0
b       0.0
c     660.0
d       0.0
e    1650.0
g       0.0
dtype: float64

In [127]:
d*f

a     110.0
b       NaN
c     660.0
d       NaN
e    1650.0
g       NaN
dtype: float64

In [128]:
d.mul(f,fill_value=1)

a     110.0
b      22.0
c     660.0
d      44.0
e    1650.0
g      40.0
dtype: float64

In [129]:
d.div(f,fill_value=0)

a    1.100000
b         inf
c    1.650000
d         inf
e    1.833333
g    0.000000
dtype: float64

In [130]:
d.div(f,fill_value=1)

a     1.100000
b    22.000000
c     1.650000
d    44.000000
e     1.833333
g     0.025000
dtype: float64

In [132]:
# Pandas의 기본 연산_02
# 기본 연산 - DataFrame_01
a={'점수 1':[10,20,30],'점수 2':[20,40,60]}
df1=pd.DataFrame(a)
df1

점수 1  점수 2
0    10    20
1    20    40
2    30    60

In [133]:
b={'점수 1':[100,200,300],'점수 3':[200,400,600]}
df2=pd.DataFrame(b)
df2

점수 1  점수 3
0   100   200
1   200   400
2   300   600

In [135]:
df3=df1+df2
df3

점수 1  점수 2  점수 3
0   110   NaN   NaN
1   220   NaN   NaN
2   330   NaN   NaN

In [136]:
df4=df1.add(df2, fill_value=0)
df4

점수 1  점수 2   점수 3
0   110  20.0  200.0
1   220  40.0  400.0
2   330  60.0  600.0

In [137]:
df5=df1.sub(df2, fill_value=0)
df5

점수 1  점수 2   점수 3
0   -90  20.0 -200.0
1  -180  40.0 -400.0
2  -270  60.0 -600.0

In [138]:
df6=df1.mul(df2, fill_value=1) # 0이 아닌 1로
df6

점수 1  점수 2   점수 3
0  1000  20.0  200.0
1  4000  40.0  400.0
2  9000  60.0  600.0

In [139]:
df7=df1.div(df2, fill_value=1) # 0이 아닌 1로
df7

점수 1  점수 2      점수 3
0   0.1  20.0  0.005000
1   0.1  40.0  0.002500
2   0.1  60.0  0.001667

In [140]:
# Pandas의 기본 연산_03
# 기본 연산 - DataFrame_02
a={'이름':['홍길동','사람 1','사람 2'],'나이':[20,30,25]}
df1=pd.DataFrame(a)
df1

이름  나이
0   홍길동  20
1  사람 1  30
2  사람 2  25

In [141]:
b={'이름':['홍길동','사람 1','사람 2'],'도시':['서울','서울','대전']}
df2=pd.DataFrame(b)
df2

이름  도시
0   홍길동  서울
1  사람 1  서울
2  사람 2  대전

In [142]:
df=pd.merge(left=df1,
               right=df2,
               how='left',
               left_on='이름',
               right_on='이름')
df

이름  나이  도시
0   홍길동  20  서울
1  사람 1  30  서울
2  사람 2  25  대전

In [143]:
x1=(df['도시']=='서울')

In [144]:
df[x1]

이름  나이  도시
0   홍길동  20  서울
1  사람 1  30  서울

In [145]:
x2=(df['도시'] != '서울')
df[x2]

이름  나이  도시
2  사람 2  25  대전

In [146]:
x3=(df['나이']<30)
df[x3]

이름  나이  도시
0   홍길동  20  서울
2  사람 2  25  대전

In [147]:
x4=(df['도시']=='서울') & (df['나이']<30)
df[x4]

이름  나이  도시
0  홍길동  20  서울

In [148]:
x5=(df['도시']=='서울') | (df['나이']<30)
df[x5]

이름  나이  도시
0   홍길동  20  서울
1  사람 1  30  서울
2  사람 2  25  대전